### ISSUE TITLE
about 10.6 How big RSA keys

### ISSUE THREAD

**Issue by byronhe** [joearms/crypto_tutorial#10]
> 10.6 How big RSA keys?
> How large should an RSA key be? The WikiPedia says the world record was
> set for RSA-76825 and has stood since 2009. This took the equivalent of 2000
> years on a single-core 2.2 GHZ AMD Operon.
> Now each additional bit doubles the complexity of the problem So RSA 1024
> bits are 10110 time more difficult to crack than the world record26 - despite
> this I’ve often seen recommendations for 2048 bits (ie 10883 times more difficult
> than RSA 1024).
> I guess we’re expecting aliens real soon ...

according to my understanding, this calculation is wrong.

since the most powerfull algorithm to crack RSA is NFS (number field sieve) , NFS is a sub-exponential  time complex algorithm , so add one bit to the key size will not result in a double of secret level, it is less than double in factor. 

https://en.wikipedia.org/wiki/General_number_field_sieve

http://crypto.stackexchange.com/questions/8687/security-strength-of-rsa-in-relation-with-the-modulus-size

**Comment by joearms** [comment]
Thanks for pointing this out - I've changed the text completely
