### ISSUE TITLE
Alice/Anne

### ISSUE THREAD

**Issue by lovasko** [joearms/crypto_tutorial#12]
In Section 10.1 you talk about _Anne_ and Bob, whereas the standard placeholders in cryptography are _Alice_ and Bob [1]. Is this intentionally changed?

It might be interesting to include other placeholders too, such as eavesdropper Eve, malicious attacker Mallory or the opponent Oscar (opponent might be viewed as a white-hat).

https://en.wikipedia.org/wiki/Alice_and_Bob

**Comment by joearms** [comment]
Anne has magically changed into Alice
